### ISSUE TITLE
Download Button doesn't function properly

### ISSUE THREAD

**Issue by errorinc0de** [GDSC-RCCIIT/gdsc-badge-generator#8]
### Mention the script affected by the bug
Name of the affected script: [main.js](https://github.com/GDSC-RCCIIT/gdsc-badge-generator/blob/master/main.js)

### Describe the bug
The download button doesn't properly downloads  the image.

### To Reproduce
Ex. Steps to reproduce the behavior:
1. Visit [index.html](https://github.com/GDSC-RCCIIT/gdsc-badge-generator/blob/master/index.html)
2. Set the Name.
3. Select the Image.
4. Click Download Button.

### Expected behavior
After clicking the download button, the image in the card should be downloaded in .png or .jpg format

### Screenshots
![Screenshot (280)](https://user-images.githubusercontent.com/54991957/135687542-6b602e6f-4da4-498c-87dd-a0016e62a232.png)

## Do you want to work on this?
- [ ] yes
- [ ] no

**Comment by RG6969** [comment]
The issue created here is because of the HTML2CANVAS library. The document is uploaded to the HTML which is causing the CORS issue as it treats the file or document from the storage as a different access point and it violates the access-allow-origin-control header of the html. I tried to fix it using dom-to-image library but i cant import the library from git as it also restricted by Cross Origin Read Blocking and i cant find any open source api for dom to image library, i need help to formulate a way to implement that library.

**Comment by AcousticCh** [comment]
i would like to try my hand at finding why it wont download if you would assign me

**Comment by RG6969** [comment]
This error only appears because it has been hosted from the clients internal storage. I have run it using VS code's live server extension it is showing no error and works perfectly. As it has been hosted from the internal storage it's treating the internal storage as different API and thus the Cross Origin Reading Resource error is occuring. I have hosted this on netlify, it is working perfectly. Once it's been hosted it will resolve the error.Till now this is the solution i propose and it also seems to be that this HTML is not fetching any file from Local environment.

https://laughing-jepsen-e29fba.netlify.app/
